on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/*"
      - "script/*"
      - "patches/*"
  workflow_dispatch:
    inputs:
      skip_release:
        description: 'Skip release related steps? (true/false)'
        required: true
        default: 'false'

env:
  version: m125-665b0e8923

jobs:
  linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target_machine: ["x64", "arm64"]
        build_type: [Release, Debug]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - run: python3 script/check_release.py --version ${{ env.version }} --build-type ${{ matrix.build_type }} --machine ${{ matrix.target_machine }}
        if: ${{ github.event.inputs.skip_release != 'true' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
      - uses: abdes/gha-setup-ninja@660f330a40aefa8d11632b3f901e92a4adb33d65
      - run: sudo ./script/prepare_linux.sh
      - run: |
          sudo apt-get update
          sudo apt-get --yes install g\+\+-9-aarch64-linux-gnu
        if: ${{ matrix.target_machine == 'arm64' }}
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/checkout.py --version ${{ env.version }}
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/build.py --build-type ${{ matrix.build_type }} --machine ${{ matrix.target_machine }}
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/archive.py --version ${{ env.version }} --build-type ${{ matrix.build_type }} --machine ${{ matrix.target_machine }}
      - uses: actions/upload-artifact@v3
        with:
          name: Skia-${{ env.version }}-linux-${{ matrix.build_type }}-${{ matrix.target_machine }}.zip
          path: '*.zip'
      - run: python3 script/release.py --version ${{ env.version }} --build-type ${{ matrix.build_type }} --machine ${{ matrix.target_machine }}
        if: ${{ github.event.inputs.skip_release != 'true' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
